(() => {
  'use strict';
  const state={token:sessionStorage.getItem('fgbd_admin_token')||'',user:'',data:null};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>'৳'+Number(n||0).toLocaleString('en-BD');
  function msg(id,text,error=false){const e=$(id);if(!e)return;e.textContent=text||'';e.className='message'+(error?' err':'');}
  async function api(action,body={},method='POST'){
    const opt={method,headers:{'Content-Type':'application/json'}};
    if(method==='GET'){const qs=new URLSearchParams({action,...body,sessionToken:state.token});const r=await fetch('/api?'+qs);return r.json();}
    opt.body=JSON.stringify({action,...body,sessionToken:state.token});const r=await fetch('/api',{...opt});const j=await r.json();if(!j.ok&&!j.setupRequired)throw new Error(j.error||'Request failed.');return j;
  }
  function showAppLoading(text='Loading your admin workspace…'){
    $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('adminUser').textContent=state.user||'Admin';
    $('stats').innerHTML='<div class="loading-card">'+esc(text)+'</div>';
    ['recentOrders','stockAlerts','productList','orderList','customerList','inventoryList','categoryList','activityList'].forEach(id=>{if($(id))$(id).innerHTML='<div class="loading-card">Loading…</div>';});
  }
  async function login(){
    const b=$('loginBtn');b.disabled=true;b.textContent='Signing in…';msg('loginMsg','');
    try{const r=await api('adminLogin',{username:$('loginUser').value.trim(),password:$('loginPass').value},'POST');
      if(r.setupRequired){msg('loginMsg','First-time password created: '+r.initialPassword+' — save it, then log in again.',false);return;}
      state.token=r.sessionToken;state.user=r.username;sessionStorage.setItem('fgbd_admin_token',state.token);
      showAppLoading();
      // Authentication is complete at this point. Load the dashboard data separately so the
      // user is not left staring at the login screen while Google Sheets is warming up.
      await boot(true);
    }catch(e){msg('loginMsg',e.message,true);}finally{b.disabled=false;b.textContent='Log in';}
  }
  async function boot(alreadyVisible=false){
    try{if(!alreadyVisible)showAppLoading('Restoring your admin session…');const r=await api('adminData',{},'GET');if(!r.ok)throw new Error(r.error||'Session expired.');state.data=r;state.user=r.username||state.user;$('adminUser').textContent=state.user;renderAll();}
    catch(e){sessionStorage.removeItem('fgbd_admin_token');state.token='';$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');msg('loginMsg',e.message,true);}
  }
  function renderAll(){renderDashboard();renderProducts();renderOrders();renderCustomers();renderInventory();renderCategories();renderActivity();renderSettings();}
  function renderDashboard(){
    const d=state.data.dashboard||{};const items=[['Sales',money(d.sales)],['Orders',d.totalOrders],['Customers',d.totalCustomers],['Products',d.totalProducts],['Active',d.activeProducts],['Low Stock',d.lowStock],['Out of Stock',d.outOfStock],['Pending',d.pendingOrders]];
    $('stats').innerHTML=items.map(x=>`<div class="stat"><small>${esc(x[0])}</small><b>${esc(x[1])}</b></div>`).join('');
    const orders=(state.data.orders||[]).slice(0,6);$('recentOrders').innerHTML=orders.length?orders.map(o=>`<div class="list-card"><div class="list-main"><strong>${esc(o.orderId)}</strong><span class="muted">${esc(o.customerName)} · ${esc(o.phone)}</span></div><div><b>${money(o.total)}</b><div class="tag">${esc(o.status)}</div></div></div>`).join(''):'<div class="empty">No orders yet.</div>';
    const low=[];(state.data.products||[]).forEach(p=>(p.variants||[]).forEach(v=>{if(v.availableStock<=0||v.availableStock<=v.reorderLevel)low.push({p,v});}));$('stockAlerts').innerHTML=low.slice(0,8).map(x=>`<div class="list-card"><div class="list-main"><strong>${esc(x.p.name)}</strong><span class="muted">${esc(x.v.sku)} · ${esc(x.v.variant||'Default')}</span></div><span class="tag ${x.v.availableStock<=0?'bad':'warn'}">${x.v.availableStock<=0?'Out of Stock':'Low Stock'} · ${x.v.availableStock}</span></div>`).join('')||'<div class="empty">No stock alerts.</div>';
  }
  function renderProducts(){
    const q=($('productSearch')?.value||'').toLowerCase(),sf=$('productStatusFilter')?.value||'';let ps=state.data.products||[];
    ps=ps.filter(p=>{const text=[p.id,p.name,p.brand,p.category,...(p.variants||[]).flatMap(v=>[v.sku,v.variant])].join(' ').toLowerCase();return !q||text.includes(q)}).filter(p=>!sf||(p.variants||[]).some(v=>v.websiteStatus===sf));
    $('productList').innerHTML=ps.map(p=>{const v=(p.variants||[])[0]||{},img=(v.images||[])[0]||'';return `<div class="list-card"><div class="product-row"><img class="product-img" src="${esc(img)}" onerror="this.style.visibility='hidden'"><div class="list-main"><strong>${esc(p.name)}</strong><span class="muted">${esc(p.id)} · ${esc(p.brand)} · ${esc(p.category)}</span><div><span class="tag">${p.variants.length} variant${p.variants.length===1?'':'s'}</span> <span class="tag ${v.availableStock<=0?'bad':v.availableStock<=v.reorderLevel?'warn':'ok'}">${v.availableStock<=0?'Out of Stock':v.availableStock<=v.reorderLevel?'Low Stock':'In Stock'}</span></div></div></div><div class="actions"><button class="secondary" data-edit="${esc(p.id)}">Edit</button><button class="secondary" data-toggle="${esc(p.id)}">${v.websiteStatus==='Published'?'Hide':'Publish'}</button><button class="danger" data-delete="${esc(p.id)}">Delete</button></div></div>`}).join('')||'<div class="empty">No products found.</div>';
    document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggle));
  }
  function openProduct(id=''){
    const p=(state.data.products||[]).find(x=>x.id===id)||{id:'',name:'',brand:'',category:'Gadget & Accessories',subcategory:'',shortDescription:'',description:'',featured:false,newArrival:false,deal:false,variants:[{sku:'',variantId:'',variant:'',costPrice:0,sellingPrice:0,oldPrice:0,stock:0,reorderLevel:10,supplier:'',offerPrice:0,websiteStatus:'Published',images:[]} ]};
    $('modalBody').innerHTML=`<h2>${id?'Edit':'Add'} Product</h2><div class="grid"><label>Product ID<input id="p_id" value="${esc(p.id)}" placeholder="Auto"></label><label>Product Name<input id="p_name" value="${esc(p.name)}"></label><label>Brand<input id="p_brand" value="${esc(p.brand)}"></label><label>Category<select id="p_category">${(state.data.categories||[]).map(c=>`<option ${c.name===p.category?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Subcategory<input id="p_sub" value="${esc(p.subcategory)}"></label><label>Short Description<input id="p_short" value="${esc(p.shortDescription)}"></label></div><label>Description<textarea id="p_desc">${esc(p.description)}</textarea></label><div class="grid"><label class="check"><input id="p_featured" type="checkbox" ${p.featured?'checked':''}> Featured</label><label class="check"><input id="p_new" type="checkbox" ${p.newArrival?'checked':''}> New Arrival</label><label class="check"><input id="p_deal" type="checkbox" ${p.deal?'checked':''}> Deal / Offer</label></div><h3>Variants</h3><div id="variantBox"></div><button class="secondary" id="addVariant">+ Add Variant</button><div class="actions"><button class="primary" id="saveProduct">Save Product</button><button class="secondary" id="cancelProduct">Cancel</button></div><div id="productMsg" class="message"></div>`;
    let variants=p.variants.length?p.variants:[];
    async function uploadImage(file, variantIndex){
      if(!file)return;
      if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('Choose a JPG, PNG, WEBP or GIF image.');
      if(file.size>6*1024*1024)throw new Error('Please choose an image under 6 MB.');
      const reader=new FileReader();
      const data=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read image.'));reader.readAsDataURL(file);});
      const r=await api('adminImageUpload',{fileName:file.name,mimeType:file.type,base64:data});
      if(!r.ok)throw new Error(r.error||'Image upload failed.');
      variants[variantIndex].images=[...(variants[variantIndex].images||[]),r.url].slice(0,4);
      renderVariants();
    }
    const renderVariants=()=>{
      $('variantBox').innerHTML=variants.map((v,i)=>{const imgs=v.images||[];return `<div class="variant-row" data-v="${i}"><input placeholder="SKU" value="${esc(v.sku)}" data-k="sku"><input placeholder="Variant" value="${esc(v.variant)}" data-k="variant"><input placeholder="Sell price" type="number" value="${v.sellingPrice||0}" data-k="sellingPrice"><input placeholder="Stock" type="number" value="${v.stock||0}" data-k="stock"><input placeholder="Offer price" type="number" value="${v.offerPrice||0}" data-k="offerPrice"><button class="danger" data-rm="${i}">×</button><div class="image-upload-area" style="grid-column:1/-1"><div class="image-previews">${imgs.map((u,j)=>`<div class="image-preview"><img src="${esc(u)}" alt="Product image"><button type="button" class="image-remove" data-img-rm="${i}" data-img-index="${j}">×</button></div>`).join('')}<button type="button" class="upload-tile" data-upload="${i}"><span>＋</span><small>Add photo</small></button></div><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple style="display:none" data-file="${i}"><div class="upload-hint">Choose photos directly from your phone gallery. Up to 4 images.</div></div></div>`}).join('')||'<div class="empty">No variants. Add one.</div>';
      document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{variants.splice(+b.dataset.rm,1);renderVariants()});
      document.querySelectorAll('[data-upload]').forEach(b=>b.onclick=()=>$(document.querySelector(`[data-file="${b.dataset.upload}"]`)).click());
      document.querySelectorAll('[data-file]').forEach(input=>input.onchange=async()=>{try{for(const f of [...input.files].slice(0,4-(variants[+input.dataset.file].images||[]).length)){await uploadImage(f,+input.dataset.file)}msg('productMsg','Image uploaded.');}catch(e){msg('productMsg',e.message,true)}input.value='';});
      document.querySelectorAll('[data-img-rm]').forEach(b=>b.onclick=()=>{const vi=+b.dataset.imgRm,ii=+b.dataset.imgIndex;variants[vi].images.splice(ii,1);renderVariants()});
    };renderVariants();
    $('addVariant').onclick=()=>{variants.push({sku:'',variant:'',sellingPrice:0,stock:0,offerPrice:0,images:[]});renderVariants()};
    $('saveProduct').onclick=async()=>{try{const rows=[...document.querySelectorAll('.variant-row')];const out=rows.map((row,i)=>{const v={...variants[i]};row.querySelectorAll('[data-k]').forEach(x=>{const k=x.dataset.k;v[k]=x.type==='number'?Number(x.value):x.value});v.images=[v.img1||'',v.img2||'',v.img3||'',v.img4||''].filter(Boolean);delete v.img1;delete v.img2;return v});if(!out.length)throw new Error('Add at least one variant.');const r=await api('adminProductSave',{product:{id:$('p_id').value.trim(),name:$('p_name').value.trim(),brand:$('p_brand').value.trim(),category:$('p_category').value,subcategory:$('p_sub').value.trim(),shortDescription:$('p_short').value.trim(),description:$('p_desc').value,featured:$('p_featured').checked,newArrival:$('p_new').checked,deal:$('p_deal').checked,variants:out}});if(!r.ok)throw new Error(r.error||'Save failed.');closeModal();await reload();}catch(e){msg('productMsg',e.message,true)}};
    $('cancelProduct').onclick=closeModal;$('modal').classList.remove('hidden');
  }
  async function deleteProduct(id){if(!confirm('Delete product '+id+'?'))return;try{await api('adminProductDelete',{productId:id});await reload()}catch(e){alert(e.message)}}
  async function toggleProduct(id){const p=(state.data.products||[]).find(x=>x.id===id);if(!p)return;const copy=JSON.parse(JSON.stringify(p));copy.variants.forEach(v=>v.websiteStatus=v.websiteStatus==='Published'?'Hidden':'Published');try{await api('adminProductSave',{product:copy});await reload()}catch(e){alert(e.message)}}
  function renderOrders(){const q=($('orderSearch')?.value||'').toLowerCase(),sf=$('orderStatusFilter')?.value||'';const os=(state.data.orders||[]).filter(o=>(!sf||o.status===sf)&&(!q||[o.orderId,o.customerName,o.phone].join(' ').toLowerCase().includes(q)));$('orderList').innerHTML=os.map(o=>`<div class="list-card"><div class="list-main"><strong>${esc(o.orderId)} · ${money(o.total)}</strong><span class="muted">${esc(o.customerName)} · ${esc(o.phone)} · ${esc(o.district)}</span><div><span class="tag">${esc(o.payment)}</span> <span class="tag">${esc(o.status)}</span></div><div class="order-items">${o.items.map(i=>`${esc(i.productName)} × ${i.qty}${i.variant?' · '+esc(i.variant):''}`).join('<br>')}</div></div><div class="actions"><button class="secondary" data-order="${esc(o.orderId)}">Manage</button></div></div>`).join('')||'<div class="empty">No orders found.</div>';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.order));}
  function openOrder(id){const o=(state.data.orders||[]).find(x=>x.orderId===id);if(!o)return;$('modalBody').innerHTML=`<h2>${esc(o.orderId)}</h2><div class="grid"><div><b>Customer</b><p>${esc(o.customerName)}<br>${esc(o.phone)}<br>${esc(o.email)}</p></div><div><b>Delivery</b><p>${esc(o.division)}, ${esc(o.district)}<br>${esc(o.address)}<br>${esc(o.note)}</p></div><div><b>Total</b><p>${money(o.total)} · ${esc(o.payment)}</p></div><div><b>Courier</b><input id="o_courier" value="${esc(o.courier)}"><input id="o_tracking" placeholder="Tracking ID" value="${esc(o.trackingId)}"></div></div><h3>Status</h3><select id="o_status">${['Pending','Confirmed','Processing','Shipped','Under Shipment','Delivered','Cancelled','Returned','Refunded'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><label>Admin note<textarea id="o_note"></textarea></label><div class="actions"><button class="primary" id="saveOrder">Save Order</button></div><h3>Items</h3>${o.items.map(i=>`<div class="list-card"><div>${esc(i.productName)}<br><span class="muted">${esc(i.sku)} · ${esc(i.variant)} · Qty ${i.qty}</span></div><b>${money(i.unitPrice*i.qty)}</b></div>`).join('')}`;$('saveOrder').onclick=async()=>{try{await api('adminOrderStatus',{orderId:id,status:$('o_status').value,note:$('o_note').value});await api('adminCourier',{orderId:id,courier:$('o_courier').value,trackingId:$('o_tracking').value});closeModal();await reload()}catch(e){alert(e.message)}};$('modal').classList.remove('hidden');}
  function renderCustomers(){const q=($('customerSearch')?.value||'').toLowerCase();const cs=(state.data.customers||[]).filter(c=>!q||[c.name,c.phone,c.email,c.district].join(' ').toLowerCase().includes(q));$('customerList').innerHTML=cs.map(c=>`<div class="list-card"><div class="list-main"><strong>${esc(c.name)}</strong><span class="muted">${esc(c.phone)} · ${esc(c.email)}</span><div>${esc(c.division)}, ${esc(c.district)}</div></div><div><b>${money(c.totalSpent)}</b><div class="muted">${c.totalOrders} orders</div></div></div>`).join('')||'<div class="empty">No customers found.</div>';}
  function renderInventory(){const arr=[];(state.data.products||[]).forEach(p=>(p.variants||[]).forEach(v=>arr.push({p,v})));$('inventoryList').innerHTML=arr.map(x=>`<div class="list-card"><div class="list-main"><strong>${esc(x.p.name)}</strong><span class="muted">${esc(x.v.sku)} · ${esc(x.v.variant)}</span></div><div><b>${x.v.availableStock}</b><div class="muted">available</div></div></div>`).join('')||'<div class="empty">No products.</div>';}
  function renderCategories(){$('categoryList').innerHTML=(state.data.categories||[]).map(c=>`<div class="list-card"><div><strong>${esc(c.name)}</strong><div class="muted">Sort ${c.sortOrder} · ${c.active?'Active':'Hidden'}</div></div><div class="actions"><button class="secondary" data-cat="${esc(c.name)}">Edit</button><button class="danger" data-cat-del="${esc(c.name)}">Delete</button></div></div>`).join('')||'<div class="empty">No categories.</div>';document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{$('categoryName').value=b.dataset.cat;const c=(state.data.categories||[]).find(x=>x.name===b.dataset.cat);$('categorySort').value=c?.sortOrder||0;$('categoryActive').checked=c?.active!==false});document.querySelectorAll('[data-cat-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete category '+b.dataset.cat+'?')){await api('adminCategoryDelete',{name:b.dataset.cat});await reload()}})}
  function renderActivity(){$('activityList').innerHTML=(state.data.activity||[]).map(a=>`<div class="list-card"><div class="list-main"><strong>${esc(a.action)} ${a.orderId?'· '+esc(a.orderId):''}</strong><span class="muted">${esc(a.timestamp)} · ${esc(a.admin)}</span><div>${esc(a.note)} ${a.status?'<span class="tag">'+esc(a.status)+'</span>':''}</div></div></div>`).join('')||'<div class="empty">No activity yet.</div>'}
  function renderSettings(){const s=state.data.settings||{};const keys=['Shop Name','Business Type','Currency','Shop Phone','WhatsApp','Email','Address','Business Hours','Inside Chattogram Delivery','Outside Chattogram Delivery','Free Delivery Threshold','Website Status'];$('settingsForm').innerHTML=keys.map(k=>`<label>${esc(k)}<input data-setting="${esc(k)}" value="${esc(s[k]||'')}"></label>`).join('')}
  async function reload(){const r=await api('adminData',{},'GET');if(!r.ok)throw new Error(r.error||'Unable to load data.');state.data=r;renderAll()}
  function closeModal(){$('modal').classList.add('hidden');$('modalBody').innerHTML=''}
  function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'})}
  $('loginForm').onsubmit=e=>{e.preventDefault();login()};$('togglePass').onclick=()=>{$('loginPass').type=$('loginPass').type==='password'?'text':'password';$('togglePass').textContent=$('loginPass').type==='password'?'Show':'Hide'};$('logoutBtn').onclick=async()=>{try{await api('adminLogout')}catch(_){}sessionStorage.removeItem('fgbd_admin_token');location.reload()};$('refreshBtn').onclick=reload;$('refreshOrdersBtn').onclick=reload;$('refreshActivityBtn').onclick=reload;$('newProductBtn').onclick=()=>openProduct();$('closeModal').onclick=closeModal;$('productSearch').oninput=renderProducts;$('productStatusFilter').onchange=renderProducts;$('orderSearch').oninput=renderOrders;$('orderStatusFilter').onchange=renderOrders;$('customerSearch').oninput=renderCustomers;$('adjustStockBtn').onclick=async()=>{try{const r=await api('adminStock',{sku:$('stockSku').value.trim(),quantity:Number($('stockQty').value)});msg('stockMsg','Stock updated: '+r.stock);await reload()}catch(e){msg('stockMsg',e.message,true)}};$('saveCategoryBtn').onclick=async()=>{try{await api('adminCategorySave',{name:$('categoryName').value.trim(),active:$('categoryActive').checked,sortOrder:Number($('categorySort').value)});await reload()}catch(e){alert(e.message)}};$('saveSettingsBtn').onclick=async()=>{try{const settings={};document.querySelectorAll('[data-setting]').forEach(x=>settings[x.dataset.setting]=x.value);await api('adminSettingsSave',{settings});msg('settingsMsg','Settings saved.');await reload()}catch(e){msg('settingsMsg',e.message,true)}};$('changePasswordBtn').onclick=async()=>{try{if($('newPassword').value!==$('confirmPassword').value)throw new Error('New passwords do not match.');const r=await api('adminChangePassword',{currentPassword:$('currentPassword').value,newPassword:$('newPassword').value});msg('passwordMsg',r.message);$('currentPassword').value='';$('newPassword').value='';$('confirmPassword').value=''}catch(e){msg('passwordMsg',e.message,true)}};document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));
  if(state.token)boot();
})();
