(() => {
  'use strict';
  const state={token:sessionStorage.getItem('fgbd_admin_token')||'',user:'',data:null};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>'৳'+Number(n||0).toLocaleString('en-BD');
  const pct=n=>Number(n||0).toFixed(1)+'%';
  const driveId=u=>{let raw=String(u||'').trim().replace(/&amp;/gi,'&');const formula=raw.match(/^=IMAGE\(\s*[\"']([^\"']+)[\"']/i);if(formula)raw=formula[1];raw=raw.replace(/^['\"]|['\"]$/g,'').trim();if(/^[A-Za-z0-9_-]{20,}$/.test(raw))return raw;let d=raw;try{d=decodeURIComponent(raw)}catch(_){}const patterns=[/(?:drive|docs)\.google\.com\/file\/d\/([A-Za-z0-9_-]{10,})/i,/(?:drive|docs)\.google\.com\/.*?[?&](?:id|fileId)=([A-Za-z0-9_-]{10,})/i,/drive\.usercontent\.google\.com\/download\?.*?[?&]id=([A-Za-z0-9_-]{10,})/i,/lh\d+\.googleusercontent\.com\/d\/([A-Za-z0-9_-]{10,})/i,/[?&](?:id|fileId)=([A-Za-z0-9_-]{10,})/i];for(const re of patterns){const m=d.match(re);if(m)return m[1]}return ''};
  const imageCandidates=u=>{const raw=String(u||'').trim(),id=driveId(raw),out=[],add=x=>{if(x&&!out.includes(x))out.push(x)};if(id){add(`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1600`);add(`https://lh3.googleusercontent.com/d/${encodeURIComponent(id)}=w1600`);add(`https://lh3.googleusercontent.com/d/${encodeURIComponent(id)}=w1200`);add(`https://drive.google.com/uc?export=view&id=${encodeURIComponent(id)}`);add(`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`);add(`https://drive.usercontent.google.com/download?id=${encodeURIComponent(id)}&export=view&confirm=t`);add(raw)}else if(/^https?:\/\//i.test(raw))add(raw);return out};
  const imageUrl=u=>imageCandidates(u)[0]||'';
  window.adminImageError=function(img){const c=imageCandidates(img.dataset.original||img.src),i=Number(img.dataset.try||0)+1;if(i<c.length){img.dataset.try=String(i);img.src=c[i];}else{img.style.visibility='hidden';}};
  function msg(id,text,error=false){const e=$(id);if(!e)return;e.textContent=text||'';e.className='message'+(error?' err':'');}
  async function api(action,body={}){
    const payload={action,...body,sessionToken:state.token};
    const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});
    const raw=await r.text();let j;try{j=raw?JSON.parse(raw):{};}catch(_){throw new Error(`API returned an invalid response (HTTP ${r.status}).`);}
    if(!r.ok||(!j.ok&&!j.setupRequired))throw new Error((j.error||`Request failed (HTTP ${r.status}).`)+(j.detail?`: ${j.detail}`:''));return j;
  }

  function showAppLoading(text='Loading your admin workspace…'){
    $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('adminUser').textContent=state.user||'Admin';
    $('stats').innerHTML='<div class="loading-card">'+esc(text)+'</div>';
    ['recentOrders','stockAlerts','productList','orderList','customerList','inventoryList','categoryList','activityList'].forEach(id=>{if($(id))$(id).innerHTML='<div class="loading-card">Loading…</div>';});
  }
  async function login(){
    const b=$('loginBtn');b.disabled=true;b.textContent='Signing in…';msg('loginMsg','');
    try{const r=await api('adminLogin',{username:$('loginUser').value.trim(),password:$('loginPass').value});
      if(r.setupRequired){msg('loginMsg','First-time password created: '+r.initialPassword+' — save it, then log in again.');return;}
      state.token=r.sessionToken;state.user=r.username;sessionStorage.setItem('fgbd_admin_token',state.token);showAppLoading();await boot(true);
    }catch(e){msg('loginMsg',e.message,true)}finally{b.disabled=false;b.textContent='Log in'}
  }
  async function boot(alreadyVisible=false){try{if(!alreadyVisible)showAppLoading('Restoring your admin session…');const r=await api('adminData');state.data=r;state.user=r.username||state.user;$('adminUser').textContent=state.user;renderAll()}catch(e){sessionStorage.removeItem('fgbd_admin_token');state.token='';$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');msg('loginMsg',e.message,true)}}
  async function reload(){const r=await api('adminData');state.data=r;state.user=r.username||state.user;renderAll()}
  let editingCategoryName='';
  function renderAll(){renderDashboard();renderProducts();renderOrders();renderCustomers();renderInventory();renderCategories();renderActivity();renderSettings()}
  function renderDashboard(){
    const d=state.data.dashboard||{};
    const items=[['Sales',money(d.sales)],['Orders',d.totalOrders],['Customers',d.totalCustomers],['Products',d.totalProducts],['Active',d.activeProducts],['Low Stock',d.lowStock],['Out of Stock',d.outOfStock],['Pending',d.pendingOrders],['Profit',money(d.profit)]];
    $('stats').innerHTML=items.map(x=>`<div class="stat"><small>${esc(x[0])}</small><b>${esc(x[1])}</b></div>`).join('');
    const orders=(state.data.orders||[]).slice(0,6);$('recentOrders').innerHTML=orders.length?orders.map(o=>`<div class="list-card"><div class="list-main"><strong>${esc(o.orderId)}</strong><span class="muted">${esc(o.customerName)} · ${esc(o.phone)}</span></div><div><b>${money(o.total)}</b><div class="tag">${esc(o.status)}</div></div></div>`).join(''):'<div class="empty">No orders yet.</div>';
    const low=[];(state.data.products||[]).forEach(p=>(p.variants||[]).forEach(v=>{if(v.availableStock<=0||v.availableStock<=v.reorderLevel)low.push({p,v})}));
    $('stockAlerts').innerHTML=low.slice(0,8).map(x=>`<div class="list-card"><div class="list-main"><strong>${esc(x.p.name)}</strong><span class="muted">${esc(x.v.sku)} · ${esc(x.v.variant||'Default')}</span></div><span class="tag ${x.v.availableStock<=0?'bad':'warn'}">${x.v.availableStock<=0?'Out of Stock':'Low Stock'} · ${x.v.availableStock}</span></div>`).join('')||'<div class="empty">No stock alerts.</div>';
  }
  function renderProducts(){
    const q=($('productSearch')?.value||'').toLowerCase(),sf=$('productStatusFilter')?.value||'';let ps=state.data.products||[];
    ps=ps.filter(p=>{const text=[p.id,p.name,p.brand,p.category,p.subcategory,...(p.variants||[]).flatMap(v=>[v.sku,v.variant])].join(' ').toLowerCase();return !q||text.includes(q)}).filter(p=>!sf||(p.variants||[]).some(v=>v.websiteStatus===sf));
    $('productList').innerHTML=ps.map(p=>{const vs=p.variants||[],v=vs[0]||{},img=(vs.flatMap(x=>x.images||[])[0])||'',profitMin=vs.length?Math.min(...vs.map(x=>Number(x.sellingPrice||0)-Number(x.costPrice||0))):0,profitMax=vs.length?Math.max(...vs.map(x=>Number(x.sellingPrice||0)-Number(x.costPrice||0))):0,available=Math.min(...vs.map(x=>Number(x.availableStock||0))),status=available<=0?'Out of Stock':vs.some(x=>Number(x.availableStock||0)<=Number(x.reorderLevel||10))?'Low Stock':'In Stock';return `<div class="list-card"><div class="product-row"><img class="product-img" src="${esc(imageUrl(img))}" data-original="${esc(img)}" data-try="0" loading="lazy" decoding="async" onerror="adminImageError(this)" alt="${esc(p.name)}"><div class="list-main"><strong>${esc(p.name)}</strong><span class="muted">${esc(p.id)} · ${esc(p.brand)} · ${esc(p.category)}</span><div><span class="tag">${vs.length} variant${vs.length===1?'':'s'}</span> <span class="tag ${status==='Out of Stock'?'bad':status==='Low Stock'?'warn':'ok'}">${status}</span> <span class="tag">Profit ${money(profitMin)}${profitMax!==profitMin?'–'+money(profitMax):''}</span></div></div></div><div class="actions"><button class="secondary" data-edit="${esc(p.id)}">Edit</button><button class="secondary" data-copy="${esc(p.id)}">Duplicate</button><button class="secondary" data-toggle="${esc(p.id)}">${vs.every(x=>x.websiteStatus==='Published')?'Hide':'Publish'}</button><button class="danger" data-delete="${esc(p.id)}">Delete</button></div></div>`}).join('')||'<div class="empty">No products found.</div>';
    document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>openProduct(b.dataset.copy,true));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggle));
  }

  function defaultVariant(){return {sku:'',variantId:'',variant:'',costPrice:0,sellingPrice:0,oldPrice:0,stock:0,reorderLevel:10,supplier:'',offerPrice:0,websiteStatus:'Published',images:[]}}
  function openProduct(id='',duplicate=false){
    const found=(state.data.products||[]).find(x=>x.id===id);const p=found?JSON.parse(JSON.stringify(found)):{id:'',name:'',brand:'',category:(state.data.categories||[])[0]?.name||'Gadget & Accessories',subcategory:'',shortDescription:'',description:'',featured:false,newArrival:false,deal:false,variants:[defaultVariant()]};
    if(duplicate){p.id='';p.name=p.name+' Copy';p.variants.forEach(v=>{v.sku='';v.variantId=''});}
    $('modalBody').innerHTML=`<h2>${id&&!duplicate?'Edit':'Add'} Product</h2><div class="grid"><label>Product ID<input id="p_id" value="${esc(p.id)}" placeholder="Auto generated" readonly></label><label>Product Name<input id="p_name" value="${esc(p.name)}" required></label><label>Brand<input id="p_brand" value="${esc(p.brand)}"></label><label>Category<select id="p_category">${(state.data.categories||[]).filter(c=>c.active!==false).sort((a,b)=>a.sortOrder-b.sortOrder).map(c=>`<option ${c.name===p.category?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Subcategory<input id="p_sub" value="${esc(p.subcategory)}"></label><label>Short Description<input id="p_short" value="${esc(p.shortDescription)}"></label></div><label>Description<textarea id="p_desc">${esc(p.description)}</textarea></label><div class="grid"><label class="check"><input id="p_featured" type="checkbox" ${p.featured?'checked':''}> Featured</label><label class="check"><input id="p_new" type="checkbox" ${p.newArrival?'checked':''}> New Arrival</label><label class="check"><input id="p_deal" type="checkbox" ${p.deal?'checked':''}> Deal / Offer</label></div><h3>Variants</h3><p class="muted">SKU and Variant SKU are automatic. You do not need to type them.</p><div id="variantBox"></div><button class="secondary" id="addVariant">+ Add Variant</button><div class="actions"><button class="primary" id="saveProduct">Save Product</button><button class="secondary" id="cancelProduct">Cancel</button></div><div id="productMsg" class="message"></div>`;
    let variants=p.variants.length?p.variants:[defaultVariant()];
    function compressImage(file){
      return new Promise((resolve,reject)=>{
        if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type))return reject(new Error('Choose JPG, PNG, WEBP or GIF images.'));
        if(file.size>12*1024*1024)return reject(new Error('Each image must be under 12 MB.'));
        const reader=new FileReader();
        reader.onload=()=>{
          const img=new Image();
          img.onload=()=>{
            const max=1600, scale=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height));
            const w=Math.max(1,Math.round((img.naturalWidth||img.width)*scale)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*scale));
            const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
            const ctx=canvas.getContext('2d',{alpha:true});ctx.drawImage(img,0,0,w,h);
            let mime='image/webp',quality=.82,data=canvas.toDataURL(mime,quality);
            if(!data.startsWith('data:image/webp')){mime='image/jpeg';quality=.82;data=canvas.toDataURL(mime,quality)}
            let attempts=0;
            while(data.length>3.2*1024*1024 && attempts<4){quality-=.12;data=canvas.toDataURL(mime,Math.max(.45,quality));attempts++}
            const ext=mime==='image/webp'?'webp':'jpg';
            resolve({fileName:(file.name.replace(/\.[^.]+$/,'')||'product')+'-optimized.'+ext,mimeType:mime,base64:data.split(',')[1],previewUrl:URL.createObjectURL(file)});
          };
          img.onerror=()=>reject(new Error('Could not read image.'));img.src=String(reader.result);
        };
        reader.onerror=()=>reject(new Error('Could not read image.'));reader.readAsDataURL(file);
      });
    }
    async function uploadImages(files,variantIndex){
      const existing=variants[variantIndex].images||[],list=[...files].slice(0,4-existing.length);if(!list.length)return;
      const previewItems=list.map(file=>({file,previewUrl:URL.createObjectURL(file)}));
      variants[variantIndex].images=[...existing,...previewItems.map(x=>x.previewUrl)].slice(0,4);renderVariants();
      msg('productMsg','Preparing images…');
      try{
        const optimized=[];
        for(let i=0;i<list.length;i++){msg('productMsg','Optimizing image '+(i+1)+' of '+list.length+'…');optimized.push(await compressImage(list[i]));}
        msg('productMsg','Uploading '+optimized.length+' image'+(optimized.length===1?'':'s')+'…');
        const r=await api('adminImageBatchUpload',{images:optimized.map(x=>({fileName:x.fileName,mimeType:x.mimeType,base64:x.base64}))});
        if(!r.ok)throw new Error(r.error||'Image upload failed.');
        const urls=(r.images||[]).map(x=>imageUrl(x.url));
        variants[variantIndex].images=[...existing,...urls].slice(0,4);
        previewItems.forEach(x=>URL.revokeObjectURL(x.previewUrl));
        renderVariants();msg('productMsg','Images uploaded successfully.');
      }catch(e){
        variants[variantIndex].images=existing.slice(0,4);previewItems.forEach(x=>URL.revokeObjectURL(x.previewUrl));renderVariants();throw e;
      }
    }
    const syncVariantInputs=()=>{
      document.querySelectorAll('.variant-row').forEach((row,i)=>{
        const v=variants[i]; if(!v)return;
        row.querySelectorAll('[data-k]').forEach(x=>{const k=x.dataset.k;v[k]=x.type==='number'?Number(x.value):x.value;});
      });
    };
    const renderVariants=()=>{
      syncVariantInputs();
      $('variantBox').innerHTML=variants.map((v,i)=>{const imgs=v.images||[],profit=Number(v.sellingPrice||0)-Number(v.costPrice||0),margin=Number(v.sellingPrice||0)>0?profit/Number(v.sellingPrice)*100:0;return `<div class="variant-row" data-v="${i}"><div class="variant-head"><b>Variant ${i+1}</b><span class="tag">SKU: ${esc(v.sku||'Auto on save')}</span></div><input placeholder="Variant name (e.g. Black)" value="${esc(v.variant)}" data-k="variant"><input placeholder="Cost price" type="number" value="${v.costPrice||0}" data-k="costPrice"><input placeholder="Selling price" type="number" value="${v.sellingPrice||0}" data-k="sellingPrice"><input placeholder="Old price" type="number" value="${v.oldPrice||0}" data-k="oldPrice"><input placeholder="Stock" type="number" value="${v.stock||0}" data-k="stock"><input placeholder="Reorder level" type="number" value="${v.reorderLevel??10}" data-k="reorderLevel"><input placeholder="Offer price" type="number" value="${v.offerPrice||0}" data-k="offerPrice"><select data-k="websiteStatus"><option ${v.websiteStatus==='Published'?'selected':''}>Published</option><option ${v.websiteStatus==='Hidden'?'selected':''}>Hidden</option><option ${v.websiteStatus==='Draft'?'selected':''}>Draft</option><option ${v.websiteStatus==='Archived'?'selected':''}>Archived</option></select><button class="danger" data-rm="${i}">Remove variant</button><div class="profit-box">Profit: <b>${money(profit)}</b> · Margin: <b>${pct(margin)}</b></div><div class="image-upload-area"><div class="image-previews">${imgs.map((u,j)=>`<div class="image-preview"><img src="${esc(imageUrl(u))}" loading="lazy" decoding="async" alt="Product image"><button type="button" class="image-remove" data-img-rm="${i}" data-img-index="${j}">×</button></div>`).join('')}<label class="upload-tile"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple data-file="${i}"><span>＋</span><small>Add photos</small></label></div><div class="upload-hint">Tap to choose directly from your phone gallery · up to 4 photos</div></div></div>`}).join('');
      document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{if(variants.length===1){alert('A product needs at least one variant.');return}variants.splice(+b.dataset.rm,1);renderVariants()});
      document.querySelectorAll('[data-file]').forEach(input=>input.onchange=async()=>{try{await uploadImages(input.files,+input.dataset.file)}catch(e){msg('productMsg',e.message,true)}input.value='' });
      document.querySelectorAll('[data-img-rm]').forEach(b=>b.onclick=()=>{variants[+b.dataset.imgRm].images.splice(+b.dataset.imgIndex,1);renderVariants()});
    };renderVariants();
    $('addVariant').onclick=()=>{variants.push(defaultVariant());renderVariants()};
    $('saveProduct').onclick=async()=>{try{syncVariantInputs();const name=$('p_name').value.trim();if(!name)throw new Error('Product name is required.');const rows=[...document.querySelectorAll('.variant-row')];const out=rows.map((row,i)=>{const v={...variants[i]};row.querySelectorAll('[data-k]').forEach(x=>{const k=x.dataset.k;v[k]=x.type==='number'?Number(x.value):x.value});v.images=[...(variants[i].images||[])].slice(0,4);return v});const r=await api('adminProductSave',{product:{id:$('p_id').value.trim(),name,brand:$('p_brand').value.trim(),category:$('p_category').value,subcategory:$('p_sub').value.trim(),shortDescription:$('p_short').value.trim(),description:$('p_desc').value,featured:$('p_featured').checked,newArrival:$('p_new').checked,deal:$('p_deal').checked,variants:out}});if(!r.ok)throw new Error(r.error||'Save failed.');closeModal();await reload();nav('products')}catch(e){msg('productMsg',e.message,true)}};
    $('cancelProduct').onclick=closeModal;$('modal').classList.remove('hidden');
  }
  async function deleteProduct(id){if(!confirm('Delete product '+id+'?'))return;try{await api('adminProductDelete',{productId:id});await reload()}catch(e){alert(e.message)}}
  async function toggleProduct(id){const p=(state.data.products||[]).find(x=>x.id===id);if(!p)return;const copy=JSON.parse(JSON.stringify(p));copy.variants.forEach(v=>v.websiteStatus=v.websiteStatus==='Published'?'Hidden':'Published');try{await api('adminProductSave',{product:copy});await reload()}catch(e){alert(e.message)}}
  function renderOrders(){const q=($('orderSearch')?.value||'').toLowerCase(),sf=$('orderStatusFilter')?.value||'';const os=(state.data.orders||[]).filter(o=>(!sf||o.status===sf)&&(!q||[o.orderId,o.customerName,o.phone,...o.items.map(i=>i.productName+' '+i.sku)].join(' ').toLowerCase().includes(q)));$('orderList').innerHTML=os.map(o=>`<div class="list-card"><div class="list-main"><strong>${esc(o.orderId)} · ${money(o.total)}</strong><span class="muted">${esc(o.customerName)} · ${esc(o.phone)} · ${esc(o.district)}</span><div><span class="tag">${esc(o.payment)}</span> <span class="tag">${esc(o.status)}</span></div><div class="order-items">${o.items.map(i=>`${esc(i.productName)} × ${i.qty}${i.variant?' · '+esc(i.variant):''} · ${esc(i.sku)}`).join('<br>')}</div></div><div class="actions"><button class="secondary" data-order="${esc(o.orderId)}">Manage</button></div></div>`).join('')||'<div class="empty">No orders found.</div>';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.order))}
  function openOrder(id){const o=(state.data.orders||[]).find(x=>x.orderId===id);if(!o)return;$('modalBody').innerHTML=`<h2>${esc(o.orderId)}</h2><div class="grid"><div><b>Customer</b><p>${esc(o.customerName)}<br>${esc(o.phone)}<br>${esc(o.email)}</p></div><div><b>Delivery</b><p>${esc(o.division)}, ${esc(o.district)}<br>${esc(o.address)}<br>${esc(o.note)}</p></div><div><b>Total</b><p>${money(o.total)} · ${esc(o.payment)}</p><p class="muted">Transaction ID: ${esc(o.transactionId||'—')}</p>${o.paymentProofUrl?`<p><a href="${esc(o.paymentProofUrl)}" target="_blank" rel="noopener">View payment proof</a></p>`:''}</div><div><b>Courier</b><input id="o_courier" value="${esc(o.courier)}"><input id="o_tracking" placeholder="Tracking ID" value="${esc(o.trackingId)}"></div></div><h3>Status</h3><select id="o_status">${['Pending','Confirmed','Processing','Shipped','Under Shipment','Delivered','Cancelled','Returned','Refunded'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><label>Payment Status<select id="o_payment"><option>Pending</option><option ${o.paymentStatus==='Paid'?'selected':''}>Paid</option><option ${o.paymentStatus==='Failed'?'selected':''}>Failed</option><option ${o.paymentStatus==='Partially Paid'?'selected':''}>Partially Paid</option><option ${o.paymentStatus==='Refunded'?'selected':''}>Refunded</option></select></label><label>Admin note<textarea id="o_note">${esc(o.adminNote||'')}</textarea></label><div class="actions"><button class="primary" id="saveOrder">Save Order</button><button class="secondary" id="closeOrder">Close</button></div><h3>Items</h3>${o.items.map(i=>`<div class="list-card"><div>${esc(i.productName)}<br><span class="muted">${esc(i.sku)} · ${esc(i.variant)} · Qty ${i.qty}</span></div><b>${money(i.unitPrice*i.qty)}</b></div>`).join('')}`;$('saveOrder').onclick=async()=>{try{await api('adminOrderUpdate',{orderId:id,status:$('o_status').value,courier:$('o_courier').value,trackingId:$('o_tracking').value,paymentStatus:$('o_payment').value,note:$('o_note').value});closeModal();await reload()}catch(e){alert(e.message)}};$('closeOrder').onclick=closeModal;$('modal').classList.remove('hidden')}
  function renderCustomers(){const q=($('customerSearch')?.value||'').toLowerCase();const cs=(state.data.customers||[]).sort((a,b)=>new Date(b.lastOrder||0)-new Date(a.lastOrder||0)).filter(c=>!q||[c.name,c.phone,c.email,c.district].join(' ').toLowerCase().includes(q));$('customerList').innerHTML=cs.map(c=>`<div class="list-card"><div class="list-main"><strong>${esc(c.name)}</strong><span class="muted">${esc(c.phone)} · ${esc(c.email)}</span><div>${esc(c.division)}, ${esc(c.district)}</div></div><div><b>${money(c.totalSpent)}</b><div class="muted">${c.totalOrders} orders</div></div></div>`).join('')||'<div class="empty">No customers found.</div>'}
  function renderInventory(){const arr=[];(state.data.products||[]).forEach(p=>(p.variants||[]).forEach(v=>arr.push({p,v})));arr.sort((a,b)=>Number(a.v.availableStock)-Number(b.v.availableStock));$('inventoryList').innerHTML=arr.map(x=>`<div class="list-card"><div class="list-main"><strong>${esc(x.p.name)}</strong><span class="muted">${esc(x.v.sku)} · ${esc(x.v.variant||'Default')}</span></div><div><b>${x.v.availableStock}</b><div class="muted">available</div></div></div>`).join('')||'<div class="empty">No products.</div>'}
  function renderCategories(){$('categoryList').innerHTML=(state.data.categories||[]).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name)).map(c=>`<div class="list-card"><div><strong>${esc(c.name)}</strong><div class="muted">Sort ${c.sortOrder} · ${c.active?'Active':'Hidden'}</div></div><div class="actions"><button class="secondary" data-cat="${esc(c.name)}">Edit</button><button class="danger" data-cat-del="${esc(c.name)}">Delete</button></div></div>`).join('')||'<div class="empty">No categories. Add one above.</div>';document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{const c=(state.data.categories||[]).find(x=>x.name===b.dataset.cat);editingCategoryName=c?.name||'';$('categoryName').value=c?.name||'';$('categorySort').value=c?.sortOrder||0;$('categoryActive').checked=c?.active!==false;nav('categories')});document.querySelectorAll('[data-cat-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete category '+b.dataset.cat+'?')){await api('adminCategoryDelete',{name:b.dataset.cat});await reload()}})}
  function renderActivity(){$('activityList').innerHTML=(state.data.activity||[]).map(a=>`<div class="list-card"><div class="list-main"><strong>${esc(a.action)} ${a.orderId?'· '+esc(a.orderId):''}</strong><span class="muted">${esc(a.timestamp)} · ${esc(a.admin)}</span><div>${esc(a.note)} ${a.status?'<span class="tag">'+esc(a.status)+'</span>':''}</div></div></div>`).join('')||'<div class="empty">No activity yet.</div>'}
  function renderSettings(){const s=state.data.settings||{};const keys=['Shop Name','Business Type','Currency','Shop Phone','WhatsApp','Email','Address','Business Hours','Inside Chattogram Delivery','Outside Chattogram Delivery','Free Delivery Threshold','Free Delivery Minimum Item Price','Free Delivery Minimum Item Count','bKash Number','bKash Type','Nagad Number','Nagad Type','Bank Name','Bank Account Name','Bank Account Number','Bank Branch District','Bank Branch Name','Bank Routing Number','Website Status'];$('settingsForm').innerHTML=keys.map(k=>`<label>${esc(k)}<input data-setting="${esc(k)}" value="${esc(s[k]||'')}"></label>`).join('')}
  function closeModal(){$('modal').classList.add('hidden');$('modalBody').innerHTML=''}
  function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});}
  $('loginForm').onsubmit=e=>{e.preventDefault();login()};$('togglePass').onclick=()=>{$('loginPass').type=$('loginPass').type==='password'?'text':'password';$('togglePass').textContent=$('loginPass').type==='password'?'Show':'Hide'};$('logoutBtn').onclick=async()=>{try{await api('adminLogout')}catch(_){}sessionStorage.removeItem('fgbd_admin_token');location.reload()};$('refreshBtn').onclick=reload;$('refreshOrdersBtn').onclick=reload;$('refreshActivityBtn').onclick=reload;$('newProductBtn').onclick=()=>openProduct();$('closeModal').onclick=closeModal;$('productSearch').oninput=renderProducts;$('productStatusFilter').onchange=renderProducts;$('orderSearch').oninput=renderOrders;$('orderStatusFilter').onchange=renderOrders;$('customerSearch').oninput=renderCustomers;$('adjustStockBtn').onclick=async()=>{try{const r=await api('adminStock',{sku:$('stockSku').value.trim(),quantity:Number($('stockQty').value)});msg('stockMsg','Stock updated: '+r.stock);await reload()}catch(e){msg('stockMsg',e.message,true)}};$('saveCategoryBtn').onclick=async()=>{try{await api('adminCategorySave',{name:$('categoryName').value.trim(),oldName:editingCategoryName,active:$('categoryActive').checked,sortOrder:Number($('categorySort').value)});editingCategoryName='';$('categoryName').value='';await reload()}catch(e){alert(e.message)}};$('saveSettingsBtn').onclick=async()=>{try{const settings={};document.querySelectorAll('[data-setting]').forEach(x=>settings[x.dataset.setting]=x.value);await api('adminSettingsSave',{settings});msg('settingsMsg','Settings saved.');await reload()}catch(e){msg('settingsMsg',e.message,true)}};$('changePasswordBtn').onclick=async()=>{try{if($('newPassword').value!==$('confirmPassword').value)throw new Error('New passwords do not match.');const r=await api('adminChangePassword',{currentPassword:$('currentPassword').value,newPassword:$('newPassword').value});msg('passwordMsg',r.message);$('currentPassword').value='';$('newPassword').value='';$('confirmPassword').value=''}catch(e){msg('passwordMsg',e.message,true)}};document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));
  if(state.token)boot();
})();
